runtime: python311

env_variables:
  PROJECT_NAME: "FastAPI Backend"
  PROJECT_DESCRIPTION: "A fast and modern API built with FastAPI for Cloud Run"
  VERSION: "1.0.0"
  API_V1_STR: "/api/v1"
  HOST: "0.0.0.0"
  PORT: "8080"
  ALLOWED_HOSTS: "*"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5

handlers:
- url: /.*
  script: auto