steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'fastapi-backend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/fastapi-backend:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8000'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'PROJECT_NAME=FastAPI Backend,PROJECT_DESCRIPTION=A fast and modern API built with FastAPI for Cloud Run,VERSION=1.0.0,API_V1_STR=/api/v1,HOST=0.0.0.0,PORT=8000,ALLOWED_HOSTS=*'

images:
  - 'gcr.io/$PROJECT_ID/fastapi-backend:$COMMIT_SHA'